modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="destinycraft2"
version="0.1188"
displayName="DestinyCraft2"
displayURL="https://twitter.com/Vanilla_JP"
credits="https://github.com/AI-Vanilla/DestinyCraft"
authors="AI_Vanilla"

[[dependencies.destinycraft2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




