modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="destinycraft2"
version="0.1131"
displayName="DestinyCraft2"
credits="https://github.com/AI-Vanilla/DestinyCraft"
displayURL="https://twitter.com/Vanilla_JP"
authors="AI_Vanilla"

[[dependencies.destinycraft2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.destinycraft2]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

